/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const GoalCategory = IDL.Variant({
  'finance' : IDL.Null,
  'other' : IDL.Null,
  'learning' : IDL.Null,
  'personal' : IDL.Null,
  'fitness' : IDL.Null,
  'career' : IDL.Null,
  'health' : IDL.Null,
});
export const CreateGoalInput = IDL.Record({
  'title' : IDL.Text,
  'targetDate' : IDL.Opt(Timestamp),
  'category' : GoalCategory,
});
export const ItemId = IDL.Nat;
export const GoalPublic = IDL.Record({
  'id' : ItemId,
  'title' : IDL.Text,
  'progressPercent' : IDL.Nat,
  'targetDate' : IDL.Opt(Timestamp),
  'linkedTaskIds' : IDL.Vec(ItemId),
  'category' : GoalCategory,
});
export const DayOfWeek = IDL.Variant({
  'tuesday' : IDL.Null,
  'wednesday' : IDL.Null,
  'saturday' : IDL.Null,
  'thursday' : IDL.Null,
  'sunday' : IDL.Null,
  'friday' : IDL.Null,
  'monday' : IDL.Null,
});
export const RoutineCategory = IDL.Variant({
  'morning' : IDL.Null,
  'evening' : IDL.Null,
  'custom' : IDL.Null,
  'work' : IDL.Null,
  'sleep' : IDL.Null,
  'workout' : IDL.Null,
});
export const CreateRoutineInput = IDL.Record({
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'name' : IDL.Text,
  'daysOfWeek' : IDL.Vec(DayOfWeek),
  'isEnabled' : IDL.Bool,
  'category' : RoutineCategory,
});
export const RoutineItemPublic = IDL.Record({
  'id' : ItemId,
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'name' : IDL.Text,
  'daysOfWeek' : IDL.Vec(DayOfWeek),
  'isEnabled' : IDL.Bool,
  'category' : RoutineCategory,
});
export const TaskCategory = IDL.Variant({
  'other' : IDL.Null,
  'learning' : IDL.Null,
  'work' : IDL.Null,
  'personal' : IDL.Null,
  'fitness' : IDL.Null,
  'health' : IDL.Null,
});
export const TaskPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const CreateTaskInput = IDL.Record({
  'title' : IDL.Text,
  'dueDate' : IDL.Opt(Timestamp),
  'category' : TaskCategory,
  'priority' : TaskPriority,
});
export const TaskPublic = IDL.Record({
  'id' : ItemId,
  'title' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'createdAt' : Timestamp,
  'dueDate' : IDL.Opt(Timestamp),
  'category' : TaskCategory,
  'priority' : TaskPriority,
});
export const ChatRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
  'systemRole' : IDL.Null,
});
export const ChatMessagePublic = IDL.Record({
  'id' : ItemId,
  'content' : IDL.Text,
  'role' : ChatRole,
  'timestamp' : Timestamp,
});
export const UserId = IDL.Principal;
export const NotificationSettings = IDL.Record({
  'habitNudges' : IDL.Bool,
  'motivationalAlerts' : IDL.Bool,
  'routineReminders' : IDL.Bool,
});
export const Preferences = IDL.Record({
  'theme' : IDL.Text,
  'notificationSettings' : NotificationSettings,
});
export const UserProfilePublic = IDL.Record({
  'displayName' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'preferences' : Preferences,
});
export const GoalProgressSummary = IDL.Record({
  'title' : IDL.Text,
  'goalId' : IDL.Nat,
  'progressPercent' : IDL.Nat,
});
export const Stats = IDL.Record({
  'tasksCompletedToday' : IDL.Nat,
  'goalProgressSummary' : IDL.Vec(GoalProgressSummary),
  'currentStreak' : IDL.Nat,
  'totalFocusTime' : IDL.Nat,
});
export const SessionType = IDL.Variant({
  'shortBreak' : IDL.Null,
  'longBreak' : IDL.Null,
  'custom' : IDL.Null,
  'pomodoro' : IDL.Null,
  'deepWork' : IDL.Null,
});
export const FocusSessionPublic = IDL.Record({
  'id' : ItemId,
  'startTime' : Timestamp,
  'duration' : IDL.Nat,
  'sessionType' : SessionType,
});
export const LogFocusSessionInput = IDL.Record({
  'startTime' : Timestamp,
  'duration' : IDL.Nat,
  'sessionType' : SessionType,
});
export const SendMessageInput = IDL.Record({ 'content' : IDL.Text });
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateGoalInput = IDL.Record({
  'id' : ItemId,
  'title' : IDL.Text,
  'progressPercent' : IDL.Nat,
  'targetDate' : IDL.Opt(Timestamp),
  'linkedTaskIds' : IDL.Vec(ItemId),
  'category' : GoalCategory,
});
export const UpdateRoutineInput = IDL.Record({
  'id' : ItemId,
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'name' : IDL.Text,
  'daysOfWeek' : IDL.Vec(DayOfWeek),
  'isEnabled' : IDL.Bool,
  'category' : RoutineCategory,
});
export const UpdateTaskInput = IDL.Record({
  'id' : ItemId,
  'title' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'dueDate' : IDL.Opt(Timestamp),
  'category' : TaskCategory,
  'priority' : TaskPriority,
});

export const idlService = IDL.Service({
  'askAI' : IDL.Func([IDL.Text], [IDL.Text], []),
  'clearChatHistory' : IDL.Func([], [IDL.Nat], []),
  'createGoal' : IDL.Func([CreateGoalInput], [GoalPublic], []),
  'createRoutine' : IDL.Func([CreateRoutineInput], [RoutineItemPublic], []),
  'createTask' : IDL.Func([CreateTaskInput], [TaskPublic], []),
  'deleteGoal' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteRoutine' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getChatHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ChatMessagePublic)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], []),
  'getMyStats' : IDL.Func([], [Stats], ['query']),
  'listMyFocusSessions' : IDL.Func(
      [],
      [IDL.Vec(FocusSessionPublic)],
      ['query'],
    ),
  'listMyGoals' : IDL.Func([], [IDL.Vec(GoalPublic)], ['query']),
  'listMyRoutines' : IDL.Func([], [IDL.Vec(RoutineItemPublic)], ['query']),
  'listMyTasks' : IDL.Func([], [IDL.Vec(TaskPublic)], ['query']),
  'logFocusSession' : IDL.Func(
      [LogFocusSessionInput],
      [FocusSessionPublic],
      [],
    ),
  'sendChatMessage' : IDL.Func([SendMessageInput], [ChatMessagePublic], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateGoal' : IDL.Func([UpdateGoalInput], [IDL.Opt(GoalPublic)], []),
  'updateRoutine' : IDL.Func(
      [UpdateRoutineInput],
      [IDL.Opt(RoutineItemPublic)],
      [],
    ),
  'updateTask' : IDL.Func([UpdateTaskInput], [IDL.Opt(TaskPublic)], []),
  'upsertMyProfile' : IDL.Func(
      [IDL.Text, Preferences],
      [UserProfilePublic],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const GoalCategory = IDL.Variant({
    'finance' : IDL.Null,
    'other' : IDL.Null,
    'learning' : IDL.Null,
    'personal' : IDL.Null,
    'fitness' : IDL.Null,
    'career' : IDL.Null,
    'health' : IDL.Null,
  });
  const CreateGoalInput = IDL.Record({
    'title' : IDL.Text,
    'targetDate' : IDL.Opt(Timestamp),
    'category' : GoalCategory,
  });
  const ItemId = IDL.Nat;
  const GoalPublic = IDL.Record({
    'id' : ItemId,
    'title' : IDL.Text,
    'progressPercent' : IDL.Nat,
    'targetDate' : IDL.Opt(Timestamp),
    'linkedTaskIds' : IDL.Vec(ItemId),
    'category' : GoalCategory,
  });
  const DayOfWeek = IDL.Variant({
    'tuesday' : IDL.Null,
    'wednesday' : IDL.Null,
    'saturday' : IDL.Null,
    'thursday' : IDL.Null,
    'sunday' : IDL.Null,
    'friday' : IDL.Null,
    'monday' : IDL.Null,
  });
  const RoutineCategory = IDL.Variant({
    'morning' : IDL.Null,
    'evening' : IDL.Null,
    'custom' : IDL.Null,
    'work' : IDL.Null,
    'sleep' : IDL.Null,
    'workout' : IDL.Null,
  });
  const CreateRoutineInput = IDL.Record({
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'name' : IDL.Text,
    'daysOfWeek' : IDL.Vec(DayOfWeek),
    'isEnabled' : IDL.Bool,
    'category' : RoutineCategory,
  });
  const RoutineItemPublic = IDL.Record({
    'id' : ItemId,
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'name' : IDL.Text,
    'daysOfWeek' : IDL.Vec(DayOfWeek),
    'isEnabled' : IDL.Bool,
    'category' : RoutineCategory,
  });
  const TaskCategory = IDL.Variant({
    'other' : IDL.Null,
    'learning' : IDL.Null,
    'work' : IDL.Null,
    'personal' : IDL.Null,
    'fitness' : IDL.Null,
    'health' : IDL.Null,
  });
  const TaskPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const CreateTaskInput = IDL.Record({
    'title' : IDL.Text,
    'dueDate' : IDL.Opt(Timestamp),
    'category' : TaskCategory,
    'priority' : TaskPriority,
  });
  const TaskPublic = IDL.Record({
    'id' : ItemId,
    'title' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'createdAt' : Timestamp,
    'dueDate' : IDL.Opt(Timestamp),
    'category' : TaskCategory,
    'priority' : TaskPriority,
  });
  const ChatRole = IDL.Variant({
    'user' : IDL.Null,
    'assistant' : IDL.Null,
    'systemRole' : IDL.Null,
  });
  const ChatMessagePublic = IDL.Record({
    'id' : ItemId,
    'content' : IDL.Text,
    'role' : ChatRole,
    'timestamp' : Timestamp,
  });
  const UserId = IDL.Principal;
  const NotificationSettings = IDL.Record({
    'habitNudges' : IDL.Bool,
    'motivationalAlerts' : IDL.Bool,
    'routineReminders' : IDL.Bool,
  });
  const Preferences = IDL.Record({
    'theme' : IDL.Text,
    'notificationSettings' : NotificationSettings,
  });
  const UserProfilePublic = IDL.Record({
    'displayName' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'preferences' : Preferences,
  });
  const GoalProgressSummary = IDL.Record({
    'title' : IDL.Text,
    'goalId' : IDL.Nat,
    'progressPercent' : IDL.Nat,
  });
  const Stats = IDL.Record({
    'tasksCompletedToday' : IDL.Nat,
    'goalProgressSummary' : IDL.Vec(GoalProgressSummary),
    'currentStreak' : IDL.Nat,
    'totalFocusTime' : IDL.Nat,
  });
  const SessionType = IDL.Variant({
    'shortBreak' : IDL.Null,
    'longBreak' : IDL.Null,
    'custom' : IDL.Null,
    'pomodoro' : IDL.Null,
    'deepWork' : IDL.Null,
  });
  const FocusSessionPublic = IDL.Record({
    'id' : ItemId,
    'startTime' : Timestamp,
    'duration' : IDL.Nat,
    'sessionType' : SessionType,
  });
  const LogFocusSessionInput = IDL.Record({
    'startTime' : Timestamp,
    'duration' : IDL.Nat,
    'sessionType' : SessionType,
  });
  const SendMessageInput = IDL.Record({ 'content' : IDL.Text });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateGoalInput = IDL.Record({
    'id' : ItemId,
    'title' : IDL.Text,
    'progressPercent' : IDL.Nat,
    'targetDate' : IDL.Opt(Timestamp),
    'linkedTaskIds' : IDL.Vec(ItemId),
    'category' : GoalCategory,
  });
  const UpdateRoutineInput = IDL.Record({
    'id' : ItemId,
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'name' : IDL.Text,
    'daysOfWeek' : IDL.Vec(DayOfWeek),
    'isEnabled' : IDL.Bool,
    'category' : RoutineCategory,
  });
  const UpdateTaskInput = IDL.Record({
    'id' : ItemId,
    'title' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'dueDate' : IDL.Opt(Timestamp),
    'category' : TaskCategory,
    'priority' : TaskPriority,
  });
  
  return IDL.Service({
    'askAI' : IDL.Func([IDL.Text], [IDL.Text], []),
    'clearChatHistory' : IDL.Func([], [IDL.Nat], []),
    'createGoal' : IDL.Func([CreateGoalInput], [GoalPublic], []),
    'createRoutine' : IDL.Func([CreateRoutineInput], [RoutineItemPublic], []),
    'createTask' : IDL.Func([CreateTaskInput], [TaskPublic], []),
    'deleteGoal' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteRoutine' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getChatHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ChatMessagePublic)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], []),
    'getMyStats' : IDL.Func([], [Stats], ['query']),
    'listMyFocusSessions' : IDL.Func(
        [],
        [IDL.Vec(FocusSessionPublic)],
        ['query'],
      ),
    'listMyGoals' : IDL.Func([], [IDL.Vec(GoalPublic)], ['query']),
    'listMyRoutines' : IDL.Func([], [IDL.Vec(RoutineItemPublic)], ['query']),
    'listMyTasks' : IDL.Func([], [IDL.Vec(TaskPublic)], ['query']),
    'logFocusSession' : IDL.Func(
        [LogFocusSessionInput],
        [FocusSessionPublic],
        [],
      ),
    'sendChatMessage' : IDL.Func([SendMessageInput], [ChatMessagePublic], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateGoal' : IDL.Func([UpdateGoalInput], [IDL.Opt(GoalPublic)], []),
    'updateRoutine' : IDL.Func(
        [UpdateRoutineInput],
        [IDL.Opt(RoutineItemPublic)],
        [],
      ),
    'updateTask' : IDL.Func([UpdateTaskInput], [IDL.Opt(TaskPublic)], []),
    'upsertMyProfile' : IDL.Func(
        [IDL.Text, Preferences],
        [UserProfilePublic],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };