/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessagePublic {
  'id' : ItemId,
  'content' : string,
  'role' : ChatRole,
  'timestamp' : Timestamp,
}
export type ChatRole = { 'user' : null } |
  { 'assistant' : null } |
  { 'systemRole' : null };
export interface CreateGoalInput {
  'title' : string,
  'targetDate' : [] | [Timestamp],
  'category' : GoalCategory,
}
export interface CreateRoutineInput {
  'startTime' : string,
  'endTime' : string,
  'name' : string,
  'daysOfWeek' : Array<DayOfWeek>,
  'isEnabled' : boolean,
  'category' : RoutineCategory,
}
export interface CreateTaskInput {
  'title' : string,
  'dueDate' : [] | [Timestamp],
  'category' : TaskCategory,
  'priority' : TaskPriority,
}
export type DayOfWeek = { 'tuesday' : null } |
  { 'wednesday' : null } |
  { 'saturday' : null } |
  { 'thursday' : null } |
  { 'sunday' : null } |
  { 'friday' : null } |
  { 'monday' : null };
export interface FocusSessionPublic {
  'id' : ItemId,
  'startTime' : Timestamp,
  'duration' : bigint,
  'sessionType' : SessionType,
}
export type GoalCategory = { 'finance' : null } |
  { 'other' : null } |
  { 'learning' : null } |
  { 'personal' : null } |
  { 'fitness' : null } |
  { 'career' : null } |
  { 'health' : null };
export interface GoalProgressSummary {
  'title' : string,
  'goalId' : bigint,
  'progressPercent' : bigint,
}
export interface GoalPublic {
  'id' : ItemId,
  'title' : string,
  'progressPercent' : bigint,
  'targetDate' : [] | [Timestamp],
  'linkedTaskIds' : Array<ItemId>,
  'category' : GoalCategory,
}
export type ItemId = bigint;
export interface LogFocusSessionInput {
  'startTime' : Timestamp,
  'duration' : bigint,
  'sessionType' : SessionType,
}
export interface NotificationSettings {
  'habitNudges' : boolean,
  'motivationalAlerts' : boolean,
  'routineReminders' : boolean,
}
export interface Preferences {
  'theme' : string,
  'notificationSettings' : NotificationSettings,
}
export type RoutineCategory = { 'morning' : null } |
  { 'evening' : null } |
  { 'custom' : null } |
  { 'work' : null } |
  { 'sleep' : null } |
  { 'workout' : null };
export interface RoutineItemPublic {
  'id' : ItemId,
  'startTime' : string,
  'endTime' : string,
  'name' : string,
  'daysOfWeek' : Array<DayOfWeek>,
  'isEnabled' : boolean,
  'category' : RoutineCategory,
}
export interface SendMessageInput { 'content' : string }
export type SessionType = { 'shortBreak' : null } |
  { 'longBreak' : null } |
  { 'custom' : null } |
  { 'pomodoro' : null } |
  { 'deepWork' : null };
export interface Stats {
  'tasksCompletedToday' : bigint,
  'goalProgressSummary' : Array<GoalProgressSummary>,
  'currentStreak' : bigint,
  'totalFocusTime' : bigint,
}
export type TaskCategory = { 'other' : null } |
  { 'learning' : null } |
  { 'work' : null } |
  { 'personal' : null } |
  { 'fitness' : null } |
  { 'health' : null };
export type TaskPriority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface TaskPublic {
  'id' : ItemId,
  'title' : string,
  'isCompleted' : boolean,
  'createdAt' : Timestamp,
  'dueDate' : [] | [Timestamp],
  'category' : TaskCategory,
  'priority' : TaskPriority,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateGoalInput {
  'id' : ItemId,
  'title' : string,
  'progressPercent' : bigint,
  'targetDate' : [] | [Timestamp],
  'linkedTaskIds' : Array<ItemId>,
  'category' : GoalCategory,
}
export interface UpdateRoutineInput {
  'id' : ItemId,
  'startTime' : string,
  'endTime' : string,
  'name' : string,
  'daysOfWeek' : Array<DayOfWeek>,
  'isEnabled' : boolean,
  'category' : RoutineCategory,
}
export interface UpdateTaskInput {
  'id' : ItemId,
  'title' : string,
  'isCompleted' : boolean,
  'dueDate' : [] | [Timestamp],
  'category' : TaskCategory,
  'priority' : TaskPriority,
}
export type UserId = Principal;
export interface UserProfilePublic {
  'displayName' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'preferences' : Preferences,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'askAI' : ActorMethod<[string], string>,
  'clearChatHistory' : ActorMethod<[], bigint>,
  'createGoal' : ActorMethod<[CreateGoalInput], GoalPublic>,
  'createRoutine' : ActorMethod<[CreateRoutineInput], RoutineItemPublic>,
  'createTask' : ActorMethod<[CreateTaskInput], TaskPublic>,
  'deleteGoal' : ActorMethod<[bigint], boolean>,
  'deleteRoutine' : ActorMethod<[bigint], boolean>,
  'deleteTask' : ActorMethod<[bigint], boolean>,
  'getChatHistory' : ActorMethod<[bigint], Array<ChatMessagePublic>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getMyStats' : ActorMethod<[], Stats>,
  'listMyFocusSessions' : ActorMethod<[], Array<FocusSessionPublic>>,
  'listMyGoals' : ActorMethod<[], Array<GoalPublic>>,
  'listMyRoutines' : ActorMethod<[], Array<RoutineItemPublic>>,
  'listMyTasks' : ActorMethod<[], Array<TaskPublic>>,
  'logFocusSession' : ActorMethod<[LogFocusSessionInput], FocusSessionPublic>,
  'sendChatMessage' : ActorMethod<[SendMessageInput], ChatMessagePublic>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateGoal' : ActorMethod<[UpdateGoalInput], [] | [GoalPublic]>,
  'updateRoutine' : ActorMethod<[UpdateRoutineInput], [] | [RoutineItemPublic]>,
  'updateTask' : ActorMethod<[UpdateTaskInput], [] | [TaskPublic]>,
  'upsertMyProfile' : ActorMethod<[string, Preferences], UserProfilePublic>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];