/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Stats {
    tasksCompletedToday: bigint;
    goalProgressSummary: Array<GoalProgressSummary>;
    currentStreak: bigint;
    totalFocusTime: bigint;
}
export interface CreateGoalInput {
    title: string;
    targetDate?: Timestamp;
    category: GoalCategory;
}
export interface LogFocusSessionInput {
    startTime: Timestamp;
    duration: bigint;
    sessionType: SessionType;
}
export interface CreateRoutineInput {
    startTime: string;
    endTime: string;
    name: string;
    daysOfWeek: Array<DayOfWeek>;
    isEnabled: boolean;
    category: RoutineCategory;
}
export interface TaskPublic {
    id: ItemId;
    title: string;
    isCompleted: boolean;
    createdAt: Timestamp;
    dueDate?: Timestamp;
    category: TaskCategory;
    priority: TaskPriority;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type ItemId = bigint;
export interface FocusSessionPublic {
    id: ItemId;
    startTime: Timestamp;
    duration: bigint;
    sessionType: SessionType;
}
export interface ChatMessagePublic {
    id: ItemId;
    content: string;
    role: ChatRole;
    timestamp: Timestamp;
}
export interface SendMessageInput {
    content: string;
}
export interface UpdateTaskInput {
    id: ItemId;
    title: string;
    isCompleted: boolean;
    dueDate?: Timestamp;
    category: TaskCategory;
    priority: TaskPriority;
}
export interface UpdateRoutineInput {
    id: ItemId;
    startTime: string;
    endTime: string;
    name: string;
    daysOfWeek: Array<DayOfWeek>;
    isEnabled: boolean;
    category: RoutineCategory;
}
export interface Preferences {
    theme: string;
    notificationSettings: NotificationSettings;
}
export interface NotificationSettings {
    habitNudges: boolean;
    motivationalAlerts: boolean;
    routineReminders: boolean;
}
export interface GoalPublic {
    id: ItemId;
    title: string;
    progressPercent: bigint;
    targetDate?: Timestamp;
    linkedTaskIds: Array<ItemId>;
    category: GoalCategory;
}
export interface CreateTaskInput {
    title: string;
    dueDate?: Timestamp;
    category: TaskCategory;
    priority: TaskPriority;
}
export interface http_header {
    value: string;
    name: string;
}
export interface UserProfilePublic {
    displayName: string;
    userId: UserId;
    createdAt: Timestamp;
    preferences: Preferences;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type UserId = Principal;
export interface RoutineItemPublic {
    id: ItemId;
    startTime: string;
    endTime: string;
    name: string;
    daysOfWeek: Array<DayOfWeek>;
    isEnabled: boolean;
    category: RoutineCategory;
}
export interface UpdateGoalInput {
    id: ItemId;
    title: string;
    progressPercent: bigint;
    targetDate?: Timestamp;
    linkedTaskIds: Array<ItemId>;
    category: GoalCategory;
}
export interface GoalProgressSummary {
    title: string;
    goalId: bigint;
    progressPercent: bigint;
}
export enum ChatRole {
    user = "user",
    assistant = "assistant",
    systemRole = "systemRole"
}
export enum DayOfWeek {
    tuesday = "tuesday",
    wednesday = "wednesday",
    saturday = "saturday",
    thursday = "thursday",
    sunday = "sunday",
    friday = "friday",
    monday = "monday"
}
export enum GoalCategory {
    finance = "finance",
    other = "other",
    learning = "learning",
    personal = "personal",
    fitness = "fitness",
    career = "career",
    health = "health"
}
export enum RoutineCategory {
    morning = "morning",
    evening = "evening",
    custom = "custom",
    work = "work",
    sleep = "sleep",
    workout = "workout"
}
export enum SessionType {
    shortBreak = "shortBreak",
    longBreak = "longBreak",
    custom = "custom",
    pomodoro = "pomodoro",
    deepWork = "deepWork"
}
export enum TaskCategory {
    other = "other",
    learning = "learning",
    work = "work",
    personal = "personal",
    fitness = "fitness",
    health = "health"
}
export enum TaskPriority {
    low = "low",
    high = "high",
    medium = "medium"
}
export interface backendInterface {
    askAI(prompt: string): Promise<string>;
    clearChatHistory(): Promise<bigint>;
    createGoal(input: CreateGoalInput): Promise<GoalPublic>;
    createRoutine(input: CreateRoutineInput): Promise<RoutineItemPublic>;
    createTask(input: CreateTaskInput): Promise<TaskPublic>;
    deleteGoal(id: bigint): Promise<boolean>;
    deleteRoutine(id: bigint): Promise<boolean>;
    deleteTask(id: bigint): Promise<boolean>;
    getChatHistory(limit: bigint): Promise<Array<ChatMessagePublic>>;
    getMyProfile(): Promise<UserProfilePublic | null>;
    getMyStats(): Promise<Stats>;
    listMyFocusSessions(): Promise<Array<FocusSessionPublic>>;
    listMyGoals(): Promise<Array<GoalPublic>>;
    listMyRoutines(): Promise<Array<RoutineItemPublic>>;
    listMyTasks(): Promise<Array<TaskPublic>>;
    logFocusSession(input: LogFocusSessionInput): Promise<FocusSessionPublic>;
    sendChatMessage(input: SendMessageInput): Promise<ChatMessagePublic>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateGoal(input: UpdateGoalInput): Promise<GoalPublic | null>;
    updateRoutine(input: UpdateRoutineInput): Promise<RoutineItemPublic | null>;
    updateTask(input: UpdateTaskInput): Promise<TaskPublic | null>;
    upsertMyProfile(displayName: string, preferences: Preferences): Promise<UserProfilePublic>;
}
import type { ChatMessagePublic as _ChatMessagePublic, ChatRole as _ChatRole, CreateGoalInput as _CreateGoalInput, CreateRoutineInput as _CreateRoutineInput, CreateTaskInput as _CreateTaskInput, DayOfWeek as _DayOfWeek, FocusSessionPublic as _FocusSessionPublic, GoalCategory as _GoalCategory, GoalPublic as _GoalPublic, ItemId as _ItemId, LogFocusSessionInput as _LogFocusSessionInput, RoutineCategory as _RoutineCategory, RoutineItemPublic as _RoutineItemPublic, SessionType as _SessionType, TaskCategory as _TaskCategory, TaskPriority as _TaskPriority, TaskPublic as _TaskPublic, Timestamp as _Timestamp, UpdateGoalInput as _UpdateGoalInput, UpdateRoutineInput as _UpdateRoutineInput, UpdateTaskInput as _UpdateTaskInput, UserProfilePublic as _UserProfilePublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async askAI(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.askAI(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.askAI(arg0);
            return result;
        }
    }
    async clearChatHistory(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.clearChatHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearChatHistory();
            return result;
        }
    }
    async createGoal(arg0: CreateGoalInput): Promise<GoalPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createGoal(to_candid_CreateGoalInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_GoalPublic_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGoal(to_candid_CreateGoalInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_GoalPublic_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRoutine(arg0: CreateRoutineInput): Promise<RoutineItemPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoutine(to_candid_CreateRoutineInput_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_RoutineItemPublic_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoutine(to_candid_CreateRoutineInput_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_RoutineItemPublic_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTask(arg0: CreateTaskInput): Promise<TaskPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(to_candid_CreateTaskInput_n24(this._uploadFile, this._downloadFile, arg0));
                return from_candid_TaskPublic_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(to_candid_CreateTaskInput_n24(this._uploadFile, this._downloadFile, arg0));
            return from_candid_TaskPublic_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteGoal(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGoal(arg0);
            return result;
        }
    }
    async deleteRoutine(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRoutine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRoutine(arg0);
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getChatHistory(arg0: bigint): Promise<Array<ChatMessagePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatHistory(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatHistory(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStats();
            return result;
        }
    }
    async listMyFocusSessions(): Promise<Array<FocusSessionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyFocusSessions();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyFocusSessions();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyGoals(): Promise<Array<GoalPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyGoals();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyGoals();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyRoutines(): Promise<Array<RoutineItemPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyRoutines();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyRoutines();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyTasks(): Promise<Array<TaskPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyTasks();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyTasks();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async logFocusSession(arg0: LogFocusSessionInput): Promise<FocusSessionPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.logFocusSession(to_candid_LogFocusSessionInput_n50(this._uploadFile, this._downloadFile, arg0));
                return from_candid_FocusSessionPublic_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logFocusSession(to_candid_LogFocusSessionInput_n50(this._uploadFile, this._downloadFile, arg0));
            return from_candid_FocusSessionPublic_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendChatMessage(arg0: SendMessageInput): Promise<ChatMessagePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.sendChatMessage(arg0);
                return from_candid_ChatMessagePublic_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendChatMessage(arg0);
            return from_candid_ChatMessagePublic_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateGoal(arg0: UpdateGoalInput): Promise<GoalPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGoal(to_candid_UpdateGoalInput_n54(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGoal(to_candid_UpdateGoalInput_n54(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRoutine(arg0: UpdateRoutineInput): Promise<RoutineItemPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRoutine(to_candid_UpdateRoutineInput_n57(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRoutine(to_candid_UpdateRoutineInput_n57(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTask(arg0: UpdateTaskInput): Promise<TaskPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(to_candid_UpdateTaskInput_n60(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(to_candid_UpdateTaskInput_n60(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async upsertMyProfile(arg0: string, arg1: Preferences): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertMyProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertMyProfile(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ChatMessagePublic_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessagePublic): ChatMessagePublic {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_ChatRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatRole): ChatRole {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_DayOfWeek_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DayOfWeek): DayOfWeek {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_FocusSessionPublic_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FocusSessionPublic): FocusSessionPublic {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_GoalCategory_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalCategory): GoalCategory {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_GoalPublic_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalPublic): GoalPublic {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_RoutineCategory_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoutineCategory): RoutineCategory {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_RoutineItemPublic_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoutineItemPublic): RoutineItemPublic {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_SessionType_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionType): SessionType {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_TaskCategory_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskCategory): TaskCategory {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_TaskPriority_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskPriority): TaskPriority {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_TaskPublic_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskPublic): TaskPublic {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GoalPublic]): GoalPublic | null {
    return value.length === 0 ? null : from_candid_GoalPublic_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RoutineItemPublic]): RoutineItemPublic | null {
    return value.length === 0 ? null : from_candid_RoutineItemPublic_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TaskPublic]): TaskPublic | null {
    return value.length === 0 ? null : from_candid_TaskPublic_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ItemId;
    startTime: string;
    endTime: string;
    name: string;
    daysOfWeek: Array<_DayOfWeek>;
    isEnabled: boolean;
    category: _RoutineCategory;
}): {
    id: ItemId;
    startTime: string;
    endTime: string;
    name: string;
    daysOfWeek: Array<DayOfWeek>;
    isEnabled: boolean;
    category: RoutineCategory;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        endTime: value.endTime,
        name: value.name,
        daysOfWeek: from_candid_vec_n19(_uploadFile, _downloadFile, value.daysOfWeek),
        isEnabled: value.isEnabled,
        category: from_candid_RoutineCategory_n22(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ItemId;
    title: string;
    isCompleted: boolean;
    createdAt: _Timestamp;
    dueDate: [] | [_Timestamp];
    category: _TaskCategory;
    priority: _TaskPriority;
}): {
    id: ItemId;
    title: string;
    isCompleted: boolean;
    createdAt: Timestamp;
    dueDate?: Timestamp;
    category: TaskCategory;
    priority: TaskPriority;
} {
    return {
        id: value.id,
        title: value.title,
        isCompleted: value.isCompleted,
        createdAt: value.createdAt,
        dueDate: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.dueDate)),
        category: from_candid_TaskCategory_n32(_uploadFile, _downloadFile, value.category),
        priority: from_candid_TaskPriority_n34(_uploadFile, _downloadFile, value.priority)
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ItemId;
    content: string;
    role: _ChatRole;
    timestamp: _Timestamp;
}): {
    id: ItemId;
    content: string;
    role: ChatRole;
    timestamp: Timestamp;
} {
    return {
        id: value.id,
        content: value.content,
        role: from_candid_ChatRole_n39(_uploadFile, _downloadFile, value.role),
        timestamp: value.timestamp
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ItemId;
    startTime: _Timestamp;
    duration: bigint;
    sessionType: _SessionType;
}): {
    id: ItemId;
    startTime: Timestamp;
    duration: bigint;
    sessionType: SessionType;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        duration: value.duration,
        sessionType: from_candid_SessionType_n45(_uploadFile, _downloadFile, value.sessionType)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ItemId;
    title: string;
    progressPercent: bigint;
    targetDate: [] | [_Timestamp];
    linkedTaskIds: Array<_ItemId>;
    category: _GoalCategory;
}): {
    id: ItemId;
    title: string;
    progressPercent: bigint;
    targetDate?: Timestamp;
    linkedTaskIds: Array<ItemId>;
    category: GoalCategory;
} {
    return {
        id: value.id,
        title: value.title,
        progressPercent: value.progressPercent,
        targetDate: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.targetDate)),
        linkedTaskIds: value.linkedTaskIds,
        category: from_candid_GoalCategory_n8(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tuesday: null;
} | {
    wednesday: null;
} | {
    saturday: null;
} | {
    thursday: null;
} | {
    sunday: null;
} | {
    friday: null;
} | {
    monday: null;
}): DayOfWeek {
    return "tuesday" in value ? DayOfWeek.tuesday : "wednesday" in value ? DayOfWeek.wednesday : "saturday" in value ? DayOfWeek.saturday : "thursday" in value ? DayOfWeek.thursday : "sunday" in value ? DayOfWeek.sunday : "friday" in value ? DayOfWeek.friday : "monday" in value ? DayOfWeek.monday : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    morning: null;
} | {
    evening: null;
} | {
    custom: null;
} | {
    work: null;
} | {
    sleep: null;
} | {
    workout: null;
}): RoutineCategory {
    return "morning" in value ? RoutineCategory.morning : "evening" in value ? RoutineCategory.evening : "custom" in value ? RoutineCategory.custom : "work" in value ? RoutineCategory.work : "sleep" in value ? RoutineCategory.sleep : "workout" in value ? RoutineCategory.workout : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    learning: null;
} | {
    work: null;
} | {
    personal: null;
} | {
    fitness: null;
} | {
    health: null;
}): TaskCategory {
    return "other" in value ? TaskCategory.other : "learning" in value ? TaskCategory.learning : "work" in value ? TaskCategory.work : "personal" in value ? TaskCategory.personal : "fitness" in value ? TaskCategory.fitness : "health" in value ? TaskCategory.health : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): TaskPriority {
    return "low" in value ? TaskPriority.low : "high" in value ? TaskPriority.high : "medium" in value ? TaskPriority.medium : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: null;
} | {
    assistant: null;
} | {
    systemRole: null;
}): ChatRole {
    return "user" in value ? ChatRole.user : "assistant" in value ? ChatRole.assistant : "systemRole" in value ? ChatRole.systemRole : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shortBreak: null;
} | {
    longBreak: null;
} | {
    custom: null;
} | {
    pomodoro: null;
} | {
    deepWork: null;
}): SessionType {
    return "shortBreak" in value ? SessionType.shortBreak : "longBreak" in value ? SessionType.longBreak : "custom" in value ? SessionType.custom : "pomodoro" in value ? SessionType.pomodoro : "deepWork" in value ? SessionType.deepWork : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    finance: null;
} | {
    other: null;
} | {
    learning: null;
} | {
    personal: null;
} | {
    fitness: null;
} | {
    career: null;
} | {
    health: null;
}): GoalCategory {
    return "finance" in value ? GoalCategory.finance : "other" in value ? GoalCategory.other : "learning" in value ? GoalCategory.learning : "personal" in value ? GoalCategory.personal : "fitness" in value ? GoalCategory.fitness : "career" in value ? GoalCategory.career : "health" in value ? GoalCategory.health : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DayOfWeek>): Array<DayOfWeek> {
    return value.map((x)=>from_candid_DayOfWeek_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessagePublic>): Array<ChatMessagePublic> {
    return value.map((x)=>from_candid_ChatMessagePublic_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FocusSessionPublic>): Array<FocusSessionPublic> {
    return value.map((x)=>from_candid_FocusSessionPublic_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GoalPublic>): Array<GoalPublic> {
    return value.map((x)=>from_candid_GoalPublic_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RoutineItemPublic>): Array<RoutineItemPublic> {
    return value.map((x)=>from_candid_RoutineItemPublic_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TaskPublic>): Array<TaskPublic> {
    return value.map((x)=>from_candid_TaskPublic_n30(_uploadFile, _downloadFile, x));
}
function to_candid_CreateGoalInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateGoalInput): _CreateGoalInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateRoutineInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateRoutineInput): _CreateRoutineInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_CreateTaskInput_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateTaskInput): _CreateTaskInput {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_DayOfWeek_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayOfWeek): _DayOfWeek {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_GoalCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalCategory): _GoalCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_LogFocusSessionInput_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LogFocusSessionInput): _LogFocusSessionInput {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_RoutineCategory_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoutineCategory): _RoutineCategory {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_SessionType_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionType): _SessionType {
    return to_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function to_candid_TaskCategory_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskCategory): _TaskCategory {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_TaskPriority_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): _TaskPriority {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateGoalInput_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateGoalInput): _UpdateGoalInput {
    return to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateRoutineInput_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateRoutineInput): _UpdateRoutineInput {
    return to_candid_record_n58(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateTaskInput_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateTaskInput): _UpdateTaskInput {
    return to_candid_record_n61(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: string;
    endTime: string;
    name: string;
    daysOfWeek: Array<DayOfWeek>;
    isEnabled: boolean;
    category: RoutineCategory;
}): {
    startTime: string;
    endTime: string;
    name: string;
    daysOfWeek: Array<_DayOfWeek>;
    isEnabled: boolean;
    category: _RoutineCategory;
} {
    return {
        startTime: value.startTime,
        endTime: value.endTime,
        name: value.name,
        daysOfWeek: to_candid_vec_n12(_uploadFile, _downloadFile, value.daysOfWeek),
        isEnabled: value.isEnabled,
        category: to_candid_RoutineCategory_n15(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    targetDate?: Timestamp;
    category: GoalCategory;
}): {
    title: string;
    targetDate: [] | [_Timestamp];
    category: _GoalCategory;
} {
    return {
        title: value.title,
        targetDate: value.targetDate ? candid_some(value.targetDate) : candid_none(),
        category: to_candid_GoalCategory_n3(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    dueDate?: Timestamp;
    category: TaskCategory;
    priority: TaskPriority;
}): {
    title: string;
    dueDate: [] | [_Timestamp];
    category: _TaskCategory;
    priority: _TaskPriority;
} {
    return {
        title: value.title,
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        category: to_candid_TaskCategory_n26(_uploadFile, _downloadFile, value.category),
        priority: to_candid_TaskPriority_n28(_uploadFile, _downloadFile, value.priority)
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: Timestamp;
    duration: bigint;
    sessionType: SessionType;
}): {
    startTime: _Timestamp;
    duration: bigint;
    sessionType: _SessionType;
} {
    return {
        startTime: value.startTime,
        duration: value.duration,
        sessionType: to_candid_SessionType_n52(_uploadFile, _downloadFile, value.sessionType)
    };
}
function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ItemId;
    title: string;
    progressPercent: bigint;
    targetDate?: Timestamp;
    linkedTaskIds: Array<ItemId>;
    category: GoalCategory;
}): {
    id: _ItemId;
    title: string;
    progressPercent: bigint;
    targetDate: [] | [_Timestamp];
    linkedTaskIds: Array<_ItemId>;
    category: _GoalCategory;
} {
    return {
        id: value.id,
        title: value.title,
        progressPercent: value.progressPercent,
        targetDate: value.targetDate ? candid_some(value.targetDate) : candid_none(),
        linkedTaskIds: value.linkedTaskIds,
        category: to_candid_GoalCategory_n3(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ItemId;
    startTime: string;
    endTime: string;
    name: string;
    daysOfWeek: Array<DayOfWeek>;
    isEnabled: boolean;
    category: RoutineCategory;
}): {
    id: _ItemId;
    startTime: string;
    endTime: string;
    name: string;
    daysOfWeek: Array<_DayOfWeek>;
    isEnabled: boolean;
    category: _RoutineCategory;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        endTime: value.endTime,
        name: value.name,
        daysOfWeek: to_candid_vec_n12(_uploadFile, _downloadFile, value.daysOfWeek),
        isEnabled: value.isEnabled,
        category: to_candid_RoutineCategory_n15(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ItemId;
    title: string;
    isCompleted: boolean;
    dueDate?: Timestamp;
    category: TaskCategory;
    priority: TaskPriority;
}): {
    id: _ItemId;
    title: string;
    isCompleted: boolean;
    dueDate: [] | [_Timestamp];
    category: _TaskCategory;
    priority: _TaskPriority;
} {
    return {
        id: value.id,
        title: value.title,
        isCompleted: value.isCompleted,
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        category: to_candid_TaskCategory_n26(_uploadFile, _downloadFile, value.category),
        priority: to_candid_TaskPriority_n28(_uploadFile, _downloadFile, value.priority)
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayOfWeek): {
    tuesday: null;
} | {
    wednesday: null;
} | {
    saturday: null;
} | {
    thursday: null;
} | {
    sunday: null;
} | {
    friday: null;
} | {
    monday: null;
} {
    return value == DayOfWeek.tuesday ? {
        tuesday: null
    } : value == DayOfWeek.wednesday ? {
        wednesday: null
    } : value == DayOfWeek.saturday ? {
        saturday: null
    } : value == DayOfWeek.thursday ? {
        thursday: null
    } : value == DayOfWeek.sunday ? {
        sunday: null
    } : value == DayOfWeek.friday ? {
        friday: null
    } : value == DayOfWeek.monday ? {
        monday: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoutineCategory): {
    morning: null;
} | {
    evening: null;
} | {
    custom: null;
} | {
    work: null;
} | {
    sleep: null;
} | {
    workout: null;
} {
    return value == RoutineCategory.morning ? {
        morning: null
    } : value == RoutineCategory.evening ? {
        evening: null
    } : value == RoutineCategory.custom ? {
        custom: null
    } : value == RoutineCategory.work ? {
        work: null
    } : value == RoutineCategory.sleep ? {
        sleep: null
    } : value == RoutineCategory.workout ? {
        workout: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskCategory): {
    other: null;
} | {
    learning: null;
} | {
    work: null;
} | {
    personal: null;
} | {
    fitness: null;
} | {
    health: null;
} {
    return value == TaskCategory.other ? {
        other: null
    } : value == TaskCategory.learning ? {
        learning: null
    } : value == TaskCategory.work ? {
        work: null
    } : value == TaskCategory.personal ? {
        personal: null
    } : value == TaskCategory.fitness ? {
        fitness: null
    } : value == TaskCategory.health ? {
        health: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == TaskPriority.low ? {
        low: null
    } : value == TaskPriority.high ? {
        high: null
    } : value == TaskPriority.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalCategory): {
    finance: null;
} | {
    other: null;
} | {
    learning: null;
} | {
    personal: null;
} | {
    fitness: null;
} | {
    career: null;
} | {
    health: null;
} {
    return value == GoalCategory.finance ? {
        finance: null
    } : value == GoalCategory.other ? {
        other: null
    } : value == GoalCategory.learning ? {
        learning: null
    } : value == GoalCategory.personal ? {
        personal: null
    } : value == GoalCategory.fitness ? {
        fitness: null
    } : value == GoalCategory.career ? {
        career: null
    } : value == GoalCategory.health ? {
        health: null
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionType): {
    shortBreak: null;
} | {
    longBreak: null;
} | {
    custom: null;
} | {
    pomodoro: null;
} | {
    deepWork: null;
} {
    return value == SessionType.shortBreak ? {
        shortBreak: null
    } : value == SessionType.longBreak ? {
        longBreak: null
    } : value == SessionType.custom ? {
        custom: null
    } : value == SessionType.pomodoro ? {
        pomodoro: null
    } : value == SessionType.deepWork ? {
        deepWork: null
    } : value;
}
function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DayOfWeek>): Array<_DayOfWeek> {
    return value.map((x)=>to_candid_DayOfWeek_n13(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
